# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Console"
  lane :dev do
    upload_to_play_store(track: 'alpha',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      apk: './platforms/android/build/outputs/apk/release/android-release.apk')
  end
  lane :test do
    upload_to_play_store(track: 'beta',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      check_superseded_tracks: true,
      apk: './platforms/android/build/outputs/apk/release/android-release.apk')
  end
  lane :prod do
    upload_to_play_store(track: 'production',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      check_superseded_tracks: true,
      apk: './platforms/android/build/outputs/apk/release/android-release.apk')
  end
end

platform :ios do
  ios_project_path = "platforms/ios/kApp.xcodeproj"

  desc "Build for IOS"
  lane :dev do
    # Recreate schemes to ensure a smooth transition from cordova to gym
    recreate_schemes(project: ios_project_path)

    #update_project_team(
    #  path: ios_project_path,
    #  teamid: "TEAMID"
    #)

    #update_provisioning_profile_specifier(xcodeproj: ios_project_path)


    gym(scheme: "awesomeproject",
        configuration: "Debug",
        clean: true,
        project: ios_project_path,
        output_directory: "target")
  end
end