version: '3.3'

services:
  kano:
    environment:
      - APP_SECRET=xxx
      - LAYERS_FILTER=OSM PLAN_IGN HUBEAU_HYDRO
      - BUILD_NUMBER
      - NODE_APP_INSTANCE
      - DB_URL
      - DATA_DB_URL
      - CESIUM_TOKEN=xxx
      - MAPILLARY_TOKEN=xxx
  hubeau-stations:
    image: kalisio/k-hubeau:hydro-stations-latest
    environment:
      - DB_URL=mongodb://mongodb:27017/kano
      - DEBUG
    networks:
      - kano
  hubeau-observations:
    image: kalisio/k-hubeau:hydro-observations-latest
    environment:
      - DB_URL=mongodb://mongodb:27017/kano
      - DEBUG
    networks:
      - kano
