FROM  node:8

MAINTAINER Kalisio <contact@kalisio.xyz>

WORKDIR /opt/kapp
COPY . /opt/kapp

RUN git clone https://github.com/kalisio/kCore.git -b test --single-branch && cd kCore && yarn install && yarn link && cd .. && yarn link kCore
RUN git clone https://github.com/kalisio/kTeam.git -b test --single-branch && cd kTeam && yarn install && yarn link kCore && yarn link && cd .. && yarn link kTeam
RUN git clone https://github.com/kalisio/kNotify.git -b test --single-branch && cd kNotify && yarn install && yarn link kCore && yarn link && cd .. && yarn link kNotify
RUN git clone https://github.com/kalisio/kMap.git -b test --single-branch && cd kMap && yarn install && yarn link kCore && yarn link && cd .. && yarn link kMap
RUN git clone https://github.com/kalisio/kEvent.git -b test --single-branch && cd kEvent && yarn install && yarn link kCore && yarn link && cd .. && yarn link kEvent
RUN yarn install
RUN npm run build

WORKDIR /opt/kapp/api

RUN yarn install
RUN yarn link kCore
RUN yarn link kTeam
RUN yarn link kNotify
RUN yarn link kMap
RUN yarn link kEvent
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
