FROM  node:8

MAINTAINER Kalisio <contact@kalisio.xyz>

WORKDIR /opt/aktnmap
COPY . /opt/aktnmap

RUN yarn install
RUN npm run build

WORKDIR /opt/aktnmap/api

RUN yarn install
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
