FROM testcafe/testcafe

MAINTAINER Luc Claustres <luc.claustres@kalisio.xyz>

WORKDIR /opt/testcafe

# Increase privileges otherwise we can't write
USER root
## Add missing modules for our tests to run
RUN npm install testcafe-vue-selectors
# Create a symlink so that we use the testcafe project as if installed
RUN cd node_modules && ln -nsf ../ testcafe
# Reset privileges
USER user
