version: '3.3'

services:
  kano:
    environment:
      - APP_SECRET=xxx
      - LAYERS_FILTER=OSM PLAN_IGN WIND_TILED GUST_TILED PRECIPITATIONS_TILED TEMPERATURE_TILED CESIUM_ELLIPSOID
      - BUILD_NUMBER
      - NODE_APP_INSTANCE
      - DB_URL
      - DATA_DB_URL
      - CESIUM_TOKEN=xxx
      - MAPILLARY_TOKEN=xxx
  weacast:
    image: weacast/weacast-api:dev
    environment:
      - APP_SECRET=yyy
      - DB_URL=mongodb://mongodb:27017/weacast
      - LOADERS=gfs
      - LOG_LEVEL
      - DEBUG
    ports:
      - "8081:8081"
    networks:
      - kano
