FROM  node:8

MAINTAINER Kalisio <contact@kalisio.xyz>

ARG APP
ARG BUILD_NUMBER

ENV BUILD_NUMBER=$BUILD_NUMBER
ENV DEBUG=
ENV NODE_APP_INSTANCE=test

WORKDIR /opt/${APP}
COPY . /opt/${APP}

WORKDIR /opt/${APP}/modules
RUN git clone https://github.com/kalisio/kCore.git -b test --single-branch && cd kCore && yarn install && yarn link && cd ..

WORKDIR /opt/${APP}/api

RUN yarn install
RUN yarn link @kalisio/kdk-core
RUN npm run build

WORKDIR /opt/${APP}

RUN yarn install
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
