FROM  node:8-buster-slim
LABEL maintainer="contact@kalisio.xyz"

ARG APP
ARG BUILD_NUMBER

ENV BUILD_NUMBER=$BUILD_NUMBER
ENV DEBUG=
ENV NODE_APP_INSTANCE=prod

COPY . /opt/${APP}

WORKDIR /opt/${APP}
RUN yarn && yarn build

WORKDIR /opt/${APP}/api
RUN yarn && yarn build

EXPOSE 8081

CMD [ "yarn", "prod" ]
