version: '3.3'

services:
  kano:
    environment:
      - LAYERS_FILTER=OSM PLAN_IGN WIND_TILED GUST_TILED PRECIPITATIONS_TILED TEMPERATURE_TILED CESIUM_ELLIPSOID
  weacast:
    image: weacast/weacast-api:dev
    environment:
      - APP_SECRET=yyy
      - DB_URL=mongodb://mongodb:27017/weacast
      - LOADERS=gfs
      - LOG_LEVEL
      - DEBUG
    ports:
      - "8081:8081"
    networks:
      - kano
