FROM  node:8

MAINTAINER Kalisio <contact@kalisio.xyz>

ARG BUILD_NUMBER
ENV BUILD_NUMBER=$BUILD_NUMBER
ENV DEBUG=
ENV NODE_APP_INSTANCE=test

WORKDIR /opt/aktnmap
COPY . /opt/aktnmap

WORKDIR /opt/aktnmap/modules
RUN git clone https://github.com/kalisio/kCore.git -b test --single-branch && cd kCore && yarn install && yarn link && cd ..
RUN git clone https://github.com/kalisio/kTeam.git -b test --single-branch && cd kTeam && yarn install && yarn link kCore && yarn link && cd ..
RUN git clone https://github.com/kalisio/kNotify.git -b test --single-branch && cd kNotify && yarn install && yarn link kCore && yarn link && cd ..
RUN git clone https://github.com/kalisio/kMap.git -b test --single-branch && cd kMap && yarn install && yarn link kCore && yarn link && cd ..
RUN git clone https://github.com/kalisio/kEvent.git -b test --single-branch && cd kEvent && yarn install && yarn link kCore && yarn link && cd ..

WORKDIR /opt/aktnmap/api

RUN yarn install
RUN yarn link kCore
RUN yarn link kTeam
RUN yarn link kNotify
RUN yarn link kMap
RUN yarn link kEvent
RUN npm run build

WORKDIR /opt/aktnmap

RUN yarn install
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
