version: '3.3'

services:
  kano:
    environment:
      - LAYERS_FILTER=OSM PLAN_IGN HUBEAU_HYDRO
  hubeau-stations:
    image: kalisio/k-hubeau:hydro-stations-latest
    environment:
      - DB_URL=mongodb://mongodb:27017/kano
      - DEBUG
    networks:
      - kano
  hubeau-observations:
    image: kalisio/k-hubeau:hydro-observations-latest
    environment:
      - DB_URL=mongodb://mongodb:27017/kano
      - DEBUG
    depends_on:
      hubeau-stations:
        condition: service_healthy
    networks:
      - kano
