FROM  node:8

MAINTAINER Kalisio <contact@kalisio.xyz>

ARG BUILD_NUMBER
ENV BUILD_NUMBER=$BUILD_NUMBER
ENV DEBUG=kalisio*,-kalisio:kCore:authorisations:hooks
ENV NODE_APP_INSTANCE=dev

WORKDIR /opt/kapp
COPY . /opt/kapp

WORKDIR /opt/kapp/modules
RUN git clone https://github.com/kalisio/kCore.git -b master --single-branch && cd kCore && yarn install && yarn link && cd ..

WORKDIR /opt/kapp/api

RUN yarn install
RUN yarn link kCore
RUN npm run build

WORKDIR /opt/kapp

RUN yarn install
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
