name: Main CI
on: [ push, workflow_dispatch ]

jobs:
  build_app:
    name: Build app
    if: ${{ !contains(github.event.head_commit.message, 'skip app') }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          GITHUB_DEVELOPMENT_PAT: ${{ secrets.GH_DEVELOPMENT_PAT }}
        run: bash ./scripts/setup_workspace.sh -k kli
      - name: Build app
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        # run: bash ./scripts/build_app.sh -p -r ${{ github.job }}
        run: bash ./scripts/build_app.sh -r ${{ github.job }}

  build_docs:
    name: Build docs
    if: ${{ contains(github.event.head_commit.message, 'build doc') }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          GITHUB_DEVELOPMENT_PAT: ${{ secrets.GH_DEVELOPMENT_PAT }}
        run: bash ./scripts/setup_workspace.sh -k nokli
      - name: Build docs
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        # run: bash ./scripts/build_docs.sh -p -r ${{ github.job }}
        run: bash ./scripts/build_docs.sh -r ${{ github.job }}
